```{r setup2, include=FALSE}
library(here)
library(dataRetrieval)
library(tidyverse)
library(trend)
library(lubridate)
library(sf)
library(nhdplusTools)
library(mapview)
knitr::opts_chunk$set(echo = TRUE)
```


# Methods

Downloaded data from USGS site number 09034250 that is along the Colorado River that was affected by the East Troublesome Fire.

## Downloaded Discharge Data

```{r}
site_no <- "09034250" 

# Discharge data pulled form the site from 10/01/1986 to 1/1/2022
q <- readNWISdv(siteNumbers = site_no,
                parameterCd = '00060',
                startDate = '1986-10-01',
                endDate = '2022-01-01') %>%
  rename(q_cfs = X_00060_00003) %>%
  addWaterYear(.) %>%
  select(-agency_cd, -X_00060_00003_cd)
```


### Mean Monthly Discharge 
```{r}
q_month_means <- q%>%
  mutate(month = month(Date),
         year = year(Date))%>%
  group_by(year, month)%>%
  summarize(q_mean = mean(q_cfs, na.rm=T))

head(q_month_means)
```

### Min Monthly Discharge 
```{r}
q_month_mins <- q%>%
  mutate(month = month(Date),
         year = year(Date))%>%
  group_by(year, month)%>%
  summarize(q_min = min(q_cfs))

head(q_month_mins)
```

### Median Monthly Discharge 
```{r}
q_month_medians <- q%>%
  mutate(month = month(Date),
         year = year(Date))%>%
  group_by(year, month)%>%
  summarize(q_median = median(q_cfs))

head(q_month_medians)
```

## Specific Conductance Data

```{r}
# Specific conductance data pulled from the site from 10/01/1986 to 1/1/2022
sc <- readNWISdv(siteNumbers = site_no,
                parameterCd = '00095',
                startDate = '1999-10-01', 
                endDate = '2021-09-30')%>%
  rename(sc = X_00095_00003)
```