---
title: "East Troublesome Fire Effect on the Watershed"
author: "Madison Thompson"
date: "5/12/2022"
site: bookdown::bookdown_site
documentclass: docs
output:
  bookdown::gitbook: default
bibliography: citations.bib
fig_caption: yes
---

# Introduction 

```{r setup, include=FALSE}
library(here)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.cap = "")
knitr::opts_chunk$set(show_col_types = FALSE)

```


# Abstract 

	Wildfires occur often and have become more crucial to understand the effects it has on a watershed. In more recent due to a variety of variables such as climate change and human disturbances these fires no longer a pure natural and healthy occurrence. Wildfires damage the land in a multitude of ways. One of the things these fires effect heavily is the watersheds. When a wildfire burns through the land high severity burned areas see the worst of the effect, but even the low burned areas are still negatively affected. By looking into discharge rate (in/day) and turbidity levels (FNU) we will be able to gain better knowledge of the effects the fire has on the land and the stream health as well. Discharge levels will help us better understand how the streamflow and the possible layout of the streams will be affected. While turbidity will help us better understand the effects on the water quality of the stream for humans and the animals dependent on the effected water sources. To understand the effects that a wildfire can have on a watershed this study investigated the East Troublesome Fire that occurred near Grandby, CO in October of 2020. This study will highlight the affects and the importance in understanding the factors that wildfires will have on watersheds. 
