# Conclusion

After the East Troublesome fire occurred there were observed negative effects on the streamflow, land, and water quality. There was found to be increased turbidity levels at high burned areas. This increase in turbidity effects the water quality to both human and animals. Increased turbidity reduces recreational appeal, which decreases quality of life for residents and causes a lost income from tourist. It also increases cost in water quality treatments centers to clean the water to be used. Turbidity also decreased photosynthesis in the streams which then decreases levels of oxygen that then negatively affect fish, invertebrates, and vegetation population. With the decrease in discharge with the higher the burn severity it shows that the vegetation and land have been negatively affected by the fire’s high severity. With the land and soil being so negatively affected that it possibly eliminated the riparian area, soil radiation was then able to create higher evaporation. This then decreases streamflow and discharge rates. This creates a negative effect for humans’ dependent on this water source due to the possible decrease in water they can obtain for use from this water source. This also effects living organism’s dependent of the water source by eliminated an ecosystem for aquatic life. Overall, it is seen wildfires do have a continuous negative effect on the watersheds even once the fire is out. If we can learn from past fires we can then better the lives of animals and people for years to come. 